# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(x) {
    .Call('_filinreg_test', PACKAGE = 'filinreg', x)
}

f_normal <- function(centers, XI, XmI, yI, ymI, M, n) {
    .Call('_filinreg_f_normal', PACKAGE = 'filinreg', centers, XI, XmI, yI, ymI, M, n)
}

f_student <- function(centers, XI, XmI, yI, ymI, M, n, nu) {
    .Call('_filinreg_f_student', PACKAGE = 'filinreg', centers, XI, XmI, yI, ymI, M, n, nu)
}

